// Action types

export const REQUEST_HOTELS_DATA = 'REQUEST_HOTELS_DATA';
export const REQUEST_HOTELS_DATA_PRICES = 'REQUEST_HOTELS_DATA_PRICES';
export const REQUEST_HOTELS_DATA_META = 'REQUEST_HOTELS_DATA_META';
export const GET_HOTELS_DATA = 'GET_HOTELS_DATA';
export const GET_HOTELS_DATA_PRICES = 'GET_HOTELS_DATA_PRICES';
export const GET_HOTELS_DATA_META = 'GET_HOTELS_DATA_META';
